title: Emocean Studio
description: >- # this means to ignore newlines until "baseurl:"
  "Solo Game Dev: Ezequiel S.S."
minimal_mistakes_skin: "aqua"
favicon: "assets/images/Logo Avatar Emocean Studio UV SF.png"
locale: "en-US"
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: America/Sao_Paulo

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ezequiel S.S."
  avatar : "assets/images/QuielDev.jpg"
  bio    : "Solo Game Dev"
  links:
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: ""
    - label: "Itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://emoceanstudio.itch.io/"
    - label: "Newgrounds"
      icon: "fas fa-fw fa-gamepad"
      url: "https://emoceanstudio.newgrounds.com/"
    - label: "Game Jolt"
      icon: "fas fa-fw fa-bolt"
      url: "https://gamejolt.com/@emoceanstudio"


footer:
  links:
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/emoceanstudio"
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/emoceanstudio.github.io"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@emoceanstudio"

defaults:

  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
